export enum Lenguaje {
  en_US = 'INGLES',
  es_ES = 'ESPAÑOL',
  fr_FR = 'FRANCES',
  de_DE = 'ALEMAN',
  it_IT = 'ITALIANO',
  pt_PT = 'PORTUGUES',
  zh_CN = 'CHINO',
  ja_JP = 'JAPONES',
  ko_KR = 'COREANO',
  ru_RU = 'RUSO',
  ar_SA = 'ARABE',
  hi_IN = 'HINDI',
  bn_BD = 'BENGALI',
  pa_IN = 'PUNJABI',
  te_IN = 'TELGU',
  mr_IN = 'MARATI',
  ta_IN = 'TAMIL',
  ur_PK = 'URDU',
  fa_IR = 'PERSA'
}
